[package]
authors = ["Dimitriye Danilovic <dimitriye@danilovic.net>"]
name = "space3"
version = "0.1.0"

[dependencies]
bitflags = "*"
image = "*"
nalgebra = "*"
ncollide = "*"
noise = "*"
rand = "*"
time = "*"
ndarray = "*"

[dependencies.glium]
version = "*"
features = ["glutin"]
