[package]
authors = ["Dimitriye Danilovic <dimitriye@danilovic.net>"]
name = "space3"
version = "0.1.0"

[dependencies]
bitflags = "0.5.0"
glium = "0.13.5"
image = "0.6.1"
nalgebra = "0.8.2"
time = "0.1.35"
