[package]
authors = ["Dimitriye Danilovic <dimitriye@danilovic.net>"]
name = "space3"
version = "0.1.0"

[dependencies]
bitflags = "*"
image = "*"
nalgebra = "*"
noise = "0.4.1"
rand = "*"
time = "*"
ndarray = "*"

[dependencies.glium]
version = "0.22.*"
features = ["glutin"]
